// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdirHjJkZK4lq68kPXr-8_KwXNBfSNs8U',
    appId: '1:152153451504:web:35942f1697651e64b74b35',
    messagingSenderId: '152153451504',
    projectId: 'cryptotrack-42898',
    authDomain: 'cryptotrack-42898.firebaseapp.com',
    storageBucket: 'cryptotrack-42898.appspot.com',
    measurementId: 'G-JE7BZG9KQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVH3ESGyF-w3_j6dkdw5D_GGQqa0aXe2s',
    appId: '1:152153451504:android:3fc76015dde306c4b74b35',
    messagingSenderId: '152153451504',
    projectId: 'cryptotrack-42898',
    storageBucket: 'cryptotrack-42898.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAx2OxowEfH6YXmBJ9Jo89jaenZB4U1oI',
    appId: '1:152153451504:ios:2cea77c20677a234b74b35',
    messagingSenderId: '152153451504',
    projectId: 'cryptotrack-42898',
    storageBucket: 'cryptotrack-42898.appspot.com',
    iosBundleId: 'com.example.cryptoTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAx2OxowEfH6YXmBJ9Jo89jaenZB4U1oI',
    appId: '1:152153451504:ios:2cea77c20677a234b74b35',
    messagingSenderId: '152153451504',
    projectId: 'cryptotrack-42898',
    storageBucket: 'cryptotrack-42898.appspot.com',
    iosBundleId: 'com.example.cryptoTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdirHjJkZK4lq68kPXr-8_KwXNBfSNs8U',
    appId: '1:152153451504:web:cbd091679ce6707bb74b35',
    messagingSenderId: '152153451504',
    projectId: 'cryptotrack-42898',
    authDomain: 'cryptotrack-42898.firebaseapp.com',
    storageBucket: 'cryptotrack-42898.appspot.com',
    measurementId: 'G-H57S32EY2X',
  );
}
